### ISSUE TITLE
SE_example and SE_example2 don't compile on mcstas-3.0 with clang and c99

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#1148]
Claims implicit declaration of functions from pol-lib/interpolation-lib/read_table-lib.

Different order of inclusion?

**Comment by ebknudsen** [comment]
This issue was related to porting the magnetic stack functions to GPU, which had left Pol_FieldBox.comp in an incomplete state. Has now been fixed to work...
